[book]
authors = ["mathcrypto"]
language = "en"
multilingual = false
src = "src"
title = "ARK-PLONK Book"
<<<<<<< HEAD
=======

[output.html]
[output.katex]

[preprocessor.katex]
macros = "macros.txt"

>>>>>>> b839b0e1c326a770ca641dd5129ed40dc18794dd
