name: plonk book

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-katex
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-katex

      - name: Build plonk book
        run: mdbook build plonk-book/

      - name: Move book to docs
        run: |
          mv ./target/doc ./docs
   
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
          publish_dir: ./docs
=======
          publish_dir: ./docs
>>>>>>> b839b0e1c326a770ca641dd5129ed40dc18794dd
